name: github_actions_practica_workflow
on: [push]
jobs:
  Linter_job:
    runs-on: ubuntu-latest
    name: Linter job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check syntax
        run: |
          npm install
          npm run lint
  Cypress-job:
    runs-on: ubuntu-latest
    name: Cypress job
    needs: Linter_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        if: always()
        id: cypress
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
          build: npm run build
          start: npm start
          config-file: cypress.json
      - name: Cypress results
        run: echo ${{ steps.cypress.outcome }} > result.txt
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifact
          path: ./result.txt
  Add-badge-job:
    runs-on: ubuntu-latest
    needs: cypress-job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: cypress-artifact
      - id: cypress-result
        run: echo "::set-output name=cypress_outcome::$(cat result.txt)"
