name: github_actions_practica_workflow
on: [push]
jobs:
  Linter_job:
    runs-on: ubuntu-latest
    name: Linter job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check syntax
        run: |
          npm install
          npm run lint
          
  Cypress_job:
    runs-on: ubuntu-latest
    name: Cypress job
    needs: Linter_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        if: always()
        id: cypress
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
          build: npm run build
          start: npm start
          config-file: cypress.json
      - name: Cypress results
        run: echo ${{ steps.cypress.outcome }} > result.txt
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifact
          path: ./result.txt
          
  Add_badge_job:
    runs-on: ubuntu-latest
    needs: Cypress_job
    if: ${{ always() }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: cypress-artifact
      - id: cypress-result
        run: echo "::set-output name=cypress_outcome::$(cat result.txt)"
      - uses: ./.github/actions/badge_readme
        with:
          result: ${{ steps.cypress-result.outputs.cypress_outcome }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          # Optional, but recommended
          commit_message: Update readme badge test result
          # Optional glob pattern of files which should be added to the commit
          file_pattern: README.md
          
  Deploy_job:
    runs-on: ubuntu-latest
    needs: Cypress-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID }}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID }} #Required

  Notification_job:
    runs-on: ubuntu-latest
    needs: [ Linter_job, Cypress_job, Add_badge_job, Deploy_job ]
    if: ${{ always() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./.github/actions/notification
        with:
          email: ${{ secrets.EMAIL }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Resultado del workflow ejecutado
          text: Se ha realizado un push en la rama main que ha provocado la ejecución del workflow nombre_repositorio_workflow con los siguientes resultados:

              - Linter_job: ${{ needs.Linter_job.result }}
              - Cypress_job: ${{ needs.Cypress_job.result }}
              - Add_badge_job: ${{ needs.Add_badge_job.result }}
              - Deploy_job: ${{ needs.Deploy_job.result }}
